### ISSUE TITLE
 Scala 2 libray TASTy compatibility

### ISSUE THREAD

**Issue by nicolasstucki** [PurpleKingdomGames/ultraviolet#108]
We found that this library does not work with the current Scala 2 library TASTy 

* See error in: https://github.com/scala/scala3/pull/19588#issuecomment-1925463405
* See what is the Scala 2 library TASTy in: https://contributors.scala-lang.org/t/scala-2-libary-tasty/6602

Please help us minimize this issue to see if it is something expected, a bug in this code base, or a bug in the compiler/library.

**Comment by davesmith00000** [comment]
Digging into this a bit, the error messages is:

```
Exception occurred while executing macro expansion.
ultraviolet.datatypes.ShaderError$UBORead: [ultraviolet] A UBO field was misread.
```

Coming from here:
https://github.com/PurpleKingdomGames/ultraviolet/blob/1149c8a6614a4119e70a20504a75a7248e19a7de/ultraviolet/shared/src/main/scala/ultraviolet/macros/ExtractUBOUtils.scala#L223

What's happening (don't know why yet) is that it tries to summon an equal number of "precision", label, and type name entries. The type names and the precisions come back with 2 values, not doubt corresponding to the two fields (see below), but the labels are missing (empty list). This is the test case class it's trying to read:

```scala
case class UBO1(TIME: highp[Float], val VIEWPORT_SIZE: vec2)
```

I've grabbed a snapshot of the syntax tree, and I'll see if I can work out where it's going wrong...

**Comment by davesmith00000** [comment]
Ok, so what's happened is that the expected structure has changed. I can make it compile by adding one new case clause. The tests fail after that, but that's another problem, screenshot below for anyone interested:

![image](https://github.com/PurpleKingdomGames/ultraviolet/assets/908709/be1e8055-cbb6-4d40-8994-ab97c8e68224)

The request was to minimise the issue, @nicolasstucki. :thinking: 

Well, the expected structure was this:

```scala
case Inlined(
              _,
              _,
              Typed(
                Block(
                  List(
                    ValDef(
                      _,
                      _,
                      Some(
                        TypeApply(
                          Select(
                            Select(
                              Apply(
                                _,
                                List(Literal(StringConstant(label)))
                              ),
                              _
                            ),
                            _
                          ),
                          _
                        )
                      )
                    )
                  ),
                  _
                ),
                _
              )
            ) =>
```

...and is now this:

```scala
case Inlined(
              _,
              _,
              Typed(
                Block(
                  List(
                    ValDef(
                      _,
                      _,
                      Some(TypeApply(Select(Literal(StringConstant(label)), _), _))
                    )
                  ),
                  _
                ),
                _
              )
            ) =>
```

However, I expect this is a _me_ problem, and what I should be doing is less fragile matching. Pro-tips welcome, but I'm thinking I just need to walk the tree until I find the `Literal(StringConstant` that I'm after and discard everything else.

**Comment by nicolasstucki** [comment]
> The request was to minimise the issue, @nicolasstucki. 🤔

Minimize, find differences, find issues.... Anything that can helps us make sure this will work with your project when we eventually stabilize it.

**Comment by nicolasstucki** [comment]
The difference in the pattern is in 
```diff
- Some(TypeApply(Select(Select(Apply(_/*f*/, List(Literal(StringConstant(label)))), _/*x*/), /*g*/), _/*T1,..Tn*/))
+ Some(TypeApply(Select(Literal(StringConstant(label)), _/*h*/), _/*U1,..Un*/))
```

which makes seems to indicate that we are matching on an expression of the form 

```diff
- f("label").x.g[T1,..,Tn]
+ "label".h[U1,..,Un]
```

@davesmith00000  what is the actual expression you are matching on? The `tree.show` and `tree.show(using Printer.TreeStructure)`.

I assume that it is something like 

```diff
```diff
- f("label").x.asInstanceOf[T]
+ "label".asInstanceOf[T]
```

**Comment by nicolasstucki** [comment]
Do you know statically which `f`, `x` you want to match on?

**Comment by davesmith00000** [comment]
Thanks @nicolasstucki, I'm not immediately following all of that (sorry, my macro-fu is weak :sweat_smile:), but I'll try and work through what you're saying a little later and see if I can come up with anything helpful.

The test case that's failing however, is already pretty minimal. You can simplify it a bit further by removing the second UBO, but there's not much to it.

https://github.com/PurpleKingdomGames/ultraviolet/blob/f0cdc17f990a75f578ce972e0a9943ad8e58da32/ultraviolet/shared/src/test/scala/ultraviolet/acceptance/GLSLUBOTests.scala#L18

What happens is that you define a case class like this:

```scala
case class UBO1(TIME: highp[Float], val VIEWPORT_SIZE: vec2)
```

Then within the shader block you say:

```scala
ubo[UBO1]
```

And it outputs this:

```glsl
layout (std140) uniform UBO1 {
  highp float TIME;
  vec2 VIEWPORT_SIZE;
};
```

**Comment by davesmith00000** [comment]
@nicolasstucki Apologies for the slow response. I've gone ahead and made this my problem (probably was anyway!).

This PR makes Ultraviolet compatible with `3.4.2-RC1-bin-20240311-02c2a6e-NIGHTLY`, and happily, works just fine with `3.4.1`, too.

https://github.com/PurpleKingdomGames/ultraviolet/pull/111

So that will be in the next release, which will be soon.
